export const SWEETALERT_SHOW = 'SWEETALERT_SHOW';
export const SWEETALERT_HIDE = 'SWEETALERT_HIDE';

export const SET_DEVICE_WIDTH = 'SET_DEVICE_WIDTH';
export const SET_DEVICE_HEIGHT = 'SET_DEVICE_HEIGHT';
export const SET_PLATFORM_OS = 'SET_PLATFORM_OS';
export const SET_APP_VERSION = 'SET_APP_VERSION';
export const SET_OLD_APP_VERSION = 'SET_OLD_APP_VERSION';
export const SET_DEVICE_TOKEN = 'SET_DEVICE_TOKEN';
export const SET_BUILD_NUMBER = 'SET_BUILD_NUMBER';
export const SET_CODEPUSH_VERSION = 'SET_CODEPUSH_VERSION';
export const REQUEST_NOTIIF_PERM_IOS = 'REQUEST_NOTIIF_PERM_IOS';

export const CONNECTION_CHECKING = 'CONNECTION_CHECKING';
export const CONNECTION_CHECKED = 'CONNECTION_CHECKED';
export const CONNECTION_ONLINE = 'CONNECTION_ONLINE';
export const CONNECTION_OFFLINE = 'CONNECTION_OFFLINE';

export const OPEN_ORI_PARTNUMBER = 'OPEN_ORI_PARTNUMBER';

export const REQUEST_CAR_MAKERS = 'REQUEST_CAR_MAKERS';
export const REQUEST_MODELS = 'REQUEST_MODELS';
export const REQUEST_MODIFICATIONS = 'REQUEST_MODIFICATIONS';
export const REQUEST_PARTS = 'REQUEST_PARTS';

export const REQUEST_FILTER_CAR_MAKERS = 'REQUEST_FILTER_CAR_MAKERS';
export const REQUEST_FILTER_MODELS = 'REQUEST_FILTER_MODELS';
export const REQUEST_FILTER_MODEL_LINES = 'REQUEST_FILTER_MODEL_LINES';
export const REQUEST_FILTER_MODIFICATIONS = 'REQUEST_FILTER_MODIFICATIONS';

export const RECEIVE_CAR_MAKERS = 'RECEIVE_CAR_MAKERS';
export const RECEIVE_YEARS = 'RECEIVE_YEARS';
export const RECEIVE_MODELS = 'RECEIVE_MODELS';
export const RECEIVE_MODIFICATIONS = 'RECEIVE_MODIFICATIONS';
export const RECEIVE_PARTS = 'RECEIVE_PARTS';

export const RECEIVE_FILTER_CAR_MAKERS = 'RECEIVE_FILTER_CAR_MAKERS';
export const RECEIVE_FILTER_MODELS = 'RECEIVE_FILTER_MODELS';
export const RECEIVE_FILTER_YEARS = 'RECEIVE_FILTER_YEARS';
export const RECEIVE_FILTER_MODEL_LINES = 'RECEIVE_FILTER_MODEL_LINES';
export const RECEIVE_FILTER_MODIFICATIONS = 'RECEIVE_FILTER_MODIFICATIONS';
export const RECEIVE_FILTER_BRANDS = 'RECEIVE_FILTER_BRANDS';
export const RECEIVE_FILTER_FAMILY = 'RECEIVE_FILTER_FAMILY';
export const RECEIVE_FILTER_CATEGORIES = 'RECEIVE_FILTER_CATEGORIES';
export const RECEIVE_FILTER_SUBCATEGORIES = 'RECEIVE_FILTER_SUBCATEGORIES';
export const RECEIVE_FILTER_SUBSUBCATEGORIES = 'RECEIVE_FILTER_SUBSUBCATEGORIES';

export const SELECT_CAR_MAKER = 'SELECT_CAR_MAKER';
export const SELECT_CAR_MAKER_VIN = 'SELECT_CAR_MAKER_VIN';
export const SELECT_YEAR = 'SELECT_YEARS';
export const SELECT_MODEL = 'SELECT_MODEL';
export const SELECT_MODIFICATION = 'SELECT_MODIFICATION';

export const SELECT_FILTER_CAR_MAKER = 'SELECT_FILTER_CAR_MAKER';
export const SELECT_FILTER_MODEL = 'SELECT_FILTER_MODEL';
export const SELECT_FILTER_YEAR = 'SELECT_FILTER_YEAR';
export const SELECT_FILTER_MODEL_LINE = 'SELECT_FILTER_MODEL_LINE';
export const SELECT_FILTER_MODIFICATION = 'SELECT_FILTER_MODIFICATION';
export const SET_FILTER_MODEL_LINE = 'SET_FILTER_MODEL_LINE';
export const SET_FILTER_MODIFICATION = 'SET_FILTER_MODIFICATION';
export const SELECT_FILTER_BRAND = 'SELECT_FILTER_BRAND';
export const SELECT_FILTER_FAMILY = 'SELECT_FILTER_FAMILY';
export const SELECT_FILTER_SORTED_BY = 'SELECT_FILTER_SORTED_BY';
export const SELECT_FILTER_CATEGORY = 'SELECT_FILTER_CATEGORY';
export const SELECT_FILTER_SUBCATEGORY = 'SELECT_FILTER_SUBCATEGORY';
export const SELECT_FILTER_SUBSUBCATEGORY = 'SELECT_FILTER_SUBSUBCATEGORY';

export const INPUT_VIN_NUMBER = 'INPUT_VIN_NUMBER';
export const INPUT_PART_NUMBER = 'INPUT_PART_NUMBER';
export const INPUT_PRICE_RANGE_MIN = 'INPUT_PRICE_RANGE_MIN';
export const INPUT_PRICE_RANGE_MAX = 'INPUT_PRICE_RANGE_MAX';

export const VALID_VIN_NUMBER = 'VALID_VIN_NUMBER';

export const CLEAR_CAR_MAKER = 'CLEAR_CAR_MAKER';
export const CLEAR_CAR_MAKER_VIN = 'CLEAR_CAR_MAKER_VIN';
export const CLEAR_YEAR = 'CLEAR_YEARS';
export const CLEAR_MODEL = 'CLEAR_MODEL';
export const CLEAR_MODIFICATION = 'CLEAR_MODIFICATION';

export const CLEAR_FILTER_CAR_MAKER = 'CLEAR_FILTER_CAR_MAKER';
export const CLEAR_FILTER_YEAR = 'CLEAR_FILTER_YEAR';
export const CLEAR_FILTER_MODEL = 'CLEAR_FILTER_MODEL';
export const CLEAR_FILTER_MODEL_LINE = 'CLEAR_FILTER_MODEL_LINE';
export const CLEAR_FILTER_MODIFICATION = 'CLEAR_FILTER_MODIFICATION';
export const CLEAR_FILTER_BRAND = 'CLEAR_FILTER_BRAND';
export const CLEAR_FILTER_FAMILY = 'CLEAR_FILTER_FAMILY';
export const CLEAR_SEARCH_PAGE = 'CLEAR_SEARCH_PAGE';
export const CLEAR_FILTER_SORTED_BY = 'CLEAR_FILTER_SORTED_BY';
export const CLEAR_FILTER_CATEGORY = 'CLEAR_FILTER_CATEGORY';
export const CLEAR_FILTER_SUBCATEGORY = 'CLEAR_FILTER_SUBCATEGORY';
export const CLEAR_FILTER_SUBSUBCATEGORY = 'CLEAR_FILTER_SUBSUBCATEGORY';

export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';

export const SET_ENABLE_SORTING = 'SET_ENABLE_SORTING';
export const SET_RESET_FILTER_DATA = 'SET_RESET_FILTER_DATA';
export const RESET_FILTER_DATA = 'RESET_FILTER_DATA';

export const REQUEST_PRODUCT_PARTINFO = 'REQUEST_PRODUCT_PARTINFO';
export const REQUEST_PRODUCT_SUPPLIERS = 'REQUEST_PRODUCT_SUPPLIERS';
export const REQUEST_PRODUCT_REPLACEMENTS = 'REQUEST_PRODUCT_REPLACEMENTS';
export const REQUEST_PRODUCT_COMPATIBILITY = 'REQUEST_PRODUCT_COMPATIBILITY';
export const REQUEST_PRODUCT_ADDTOCART = 'REQUEST_PRODUCT_ADDTOCART';

export const RECEIVE_PRODUCT_PARTINFO = 'RECEIVE_PRODUCT_PARTINFO';
export const RECEIVE_PRODUCT_SUPPLIERS = 'RECEIVE_PRODUCT_SUPPLIERS';
export const RECEIVE_PRODUCT_REPLACEMENTS = 'RECEIVE_PRODUCT_REPLACEMENTS';
export const RECEIVE_PRODUCT_COMPATIBILITY = 'RECEIVE_PRODUCT_COMPATIBILITY';
export const RECEIVE_PRODUCT_ADDTOCART = 'RECEIVE_PRODUCT_ADDTOCART';
export const RECEIVE_PIN_INFO = 'RECEIVE_PIN_INFO';
export const PRODUCT_ADDEDTOCART = 'PRODUCT_ADDEDTOCART';

export const RECEIVE_ERROR_CAR_MAKERS = 'RECEIVE_ERROR_CAR_MAKERS';
export const RECEIVE_ERROR_YEARS = 'RECEIVE_ERROR_YEARS';
export const RECEIVE_ERROR_MODELS = 'RECEIVE_ERROR_MODELS';
export const RECEIVE_ERROR_MODIFICATIONS = 'RECEIVE_ERROR_MODIFICATIONS';
export const RECEIVE_ERROR_PARTS = 'RECEIVE_ERROR_PARTS';

export const RECEIVE_ERROR_FILTER_CAR_MAKERS = 'RECEIVE_ERROR_FILTER_CAR_MAKERS';
export const RECEIVE_ERROR_FILTER_MODELS = 'RECEIVE_ERROR_FILTER_MODELS';
export const RECEIVE_ERROR_FILTER_MODEL_LINES = 'RECEIVE_ERROR_FILTER_MODEL_LINES';
export const RECEIVE_ERROR_FILTER_MODIFICATIONS = 'RECEIVE_ERROR_FILTER_MODIFICATIONS';
export const RECEIVE_ERROR_FILTER_BRANDS = 'RECEIVE_ERROR_FILTER_BRANDS';
export const RECEIVE_ERROR_FILTER_FAMILY = 'RECEIVE_ERROR_FILTER_FAMILY';
export const RECEIVE_ERROR_FILTER_CATEGORIES = 'RECEIVE_ERROR_FILTER_CATEGORIES';

export const RECEIVE_ERROR_PRODUCT_PARTINFO = 'RECEIVE_ERROR_PRODUCT_PARTINFO';
export const RECEIVE_ERROR_PRODUCT_SUPPLIERS = 'RECEIVE_ERROR_PRODUCT_SUPPLIERS';
export const RECEIVE_ERROR_PRODUCT_REPLACEMENTS = 'RECEIVE_ERROR_PRODUCT_REPLACEMENTS';
export const RECEIVE_ERROR_PRODUCT_COMPATIBILITY = 'RECEIVE_ERROR_PRODUCT_COMPATIBILITY';
export const RECEIVE_ERROR_PRODUCT_ADDTOCART = 'RECEIVE_ERROR_PRODUCT_ADDTOCART';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_DRAFT_PRODUCT_TO_CART = 'ADD_DRAFT_PRODUCT_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const UPDATE_QUANTITY_CART = 'UPDATE_QUANTITY_CART';
export const REMOVE_LOCAL_PRODUCTS_FROM_CART = 'REMOVE_LOCAL_PRODUCTS_FROM_CART';
export const UPDATE_CART_INFO = 'UPDATE_CART_INFO';
export const CLEAR_CART = 'CLEAR_CART';
export const REQUEST_CART_PRODUCTS = 'REQUEST_CART_PRODUCTS';
export const RECEIVE_CART_PRODUCTS = 'RECEIVE_CART_PRODUCTS';
export const RECEIVE_ERROR_CART_PRODUCTS = 'RECEIVE_ERROR_CART_PRODUCTS';
export const RECEIVE_CART_CUID = 'RECEIVE_CART_CUID';
export const RECEIVE_CART_DRAFT_CUID = 'RECEIVE_CART_DRAFT_CUID';

export const REQUEST_LOAD_PROFILE = 'REQUEST_LOAD_PROFILE';
export const RECEIVE_LOAD_PROFILE = 'RECEIVE_LOAD_PROFILE';
export const RECEIVE_ERROR_LOAD_PROFILE = 'RECEIVE_ERROR_LOAD_PROFILE';
export const RESET_LOADED_PROFILE_STATE = 'RESET_LOADED_PROFILE_STATE';

export const CHECKOUT_GO_TO_STEP = 'CHECKOUT_GO_TO_STEP';
export const CHECKOUT_SET_USER_INFO = 'CHECKOUT_SET_USER_INFO';
export const CHECKOUT_SET_DELIVERY_INFO = 'CHECKOUT_SET_DELIVERY_INFO';
export const CHECKOUT_SAVE_DELIVERY_INFO = 'CHECKOUT_SAVE_DELIVERY_INFO';
export const CHECKOUT_SET_REVIEW_STEP = 'CHECKOUT_SET_REVIEW_STEP';
export const CHECKOUT_UPDATE_STEPS = 'CHECKOUT_UPDATE_STEPS';
export const CHECKOUT_UPDATE_REVIEW_CART = 'CHECKOUT_UPDATE_REVIEW_CART';
export const CHECKOUT_UPDATE_QUERY_CART = 'CHECKOUT_UPDATE_QUERY_CART';
export const CHECKOUT_UPDATE_PAYMENT_METHOD = 'CHECKOUT_UPDATE_PAYMENT_METHOD';
export const CHECKOUT_RESET_TO_DELIVERY = 'CHECKOUT_RESET_TO_DELIVERY';
export const CHECKOUT_RESET_DOUBLE_PAYMENT = 'CHECKOUT_RESET_DOUBLE_PAYMENT';
export const OFFLINE_CHECKOUT_USER_INFO_LOADED = 'OFFLINE_CHECKOUT_USER_INFO_LOADED';
export const OFFLINE_CHECKOUT_DELIVERY_INFO_LOADED = 'OFFLINE_CHECKOUT_DELIVERY_INFO_LOADED';

export const REQUEST_DELIVERY_VALIDATE_PIN = 'REQUEST_DELIVERY_VALIDATE_PIN';
export const RECEIVE_DELIVERY_VALIDATE_PIN = 'RECEIVE_DELIVERY_VALIDATE_PIN';
export const RECEIVE_DELIVERY_ERROR_VALIDATE_PIN = 'RECEIVE_DELIVERY_ERROR_VALIDATE_PIN';
export const REQUEST_DELIVERY_AVAILABLE_PAYMENT_METHODS = 'REQUEST_DELIVERY_AVAILABLE_PAYMENT_METHODS';
export const RECEIVE_DELIVERY_AVAILABLE_PAYMENT_METHODS = 'RECEIVE_DELIVERY_AVAILABLE_PAYMENT_METHODS';
export const RECEIVE_DELIVERY_ERROR_AVAILABLE_PAYMENT_METHODS = 'RECEIVE_DELIVERY_ERROR_AVAILABLE_PAYMENT_METHODS';

export const SET_USER_INFO_FACEBOOK = 'SET_USER_INFO_FACEBOOK';
export const SET_USER_INFO_EMAIL = 'SET_USER_INFO_EMAIL';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_MODIF_USER_INFO = 'SET_MODIF_USER_INFO';
export const REQUEST_AUTH = 'REQUEST_AUTH';
export const RECEIVE_ERROR_AUTH = 'RECEIVE_ERROR_AUTH';
export const RECEIVE_ERROR_REGISTER = 'RECEIVE_ERROR_REGISTER';
export const REQUEST_REFRESH_TOKEN = 'REQUEST_REFRESH_TOKEN';
export const RECEIVE_REFRESH_TOKEN = 'RECEIVE_REFRESH_TOKEN';
export const RECEIVE_ERROR_REFRESH_TOKEN = 'RECEIVE_ERROR_REFRESH_TOKEN';
export const FIRE_FRESHDESK_MODAL = 'FIRE_FRESHDESK_MODAL';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';
export const OFFLINE_USER_LOADED = 'OFFLINE_USER_LOADED';
export const LOG_OUT = 'LOG_OUT';
export const SIGNED_UP = 'SIGNED_UP';
export const REQUEST_PASSWORD_RECOVERY = 'REQUEST_PASSWORD_RECOVERY';
export const SENT_PASSWORD_RECOVERY = 'SENT_PASSWORD_RECOVERY';
export const REQUEST_CHECK_EMAIL = 'REQUEST_CHECK_EMAIL';
export const RECEIVE_CHECK_EMAIL = 'RECEIVE_CHECK_EMAIL';
export const CHECKOUT_STEP_CHANGE_EMAIL = 'CHECKOUT_STEP_CHANGE_EMAIL';

export const REQUEST_REVIEW_CART = 'REQUEST_REVIEW_CART';
export const RECEIVE_REVIEW_CART = 'RECEIVE_REVIEW_CART';
export const RECEIVE_ERROR_REVIEW_CART = 'RECEIVE_ERROR_REVIEW_CART';

export const REQUEST_CREATE_ORDER = 'REQUEST_CREATE_ORDER';
export const RECEIVE_ORDER = 'RECEIVE_ORDER';
export const RECEIVE_ERROR_CREATE_ORDER = 'RECEIVE_ERROR_CREATE_ORDER';

export const REQUEST_SUCCESS_ORDER = 'REQUEST_SUCCESS_ORDER';
export const RECEIVE_SUCCESS_ORDER = 'RECEIVE_SUCCESS_ORDER';
export const RECEIVE_ERROR_SUCCESS_ORDER = 'RECEIVE_ERROR_SUCCESS_ORDER';

export const REQUEST_ORDERS = 'REQUEST_ORDERS';
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export const RECEIVE_ERROR_ORDERS = 'RECEIVE_ERROR_ORDERS';
export const REQUEST_SELECTED_ORDER = 'REQUEST_SELECTED_ORDER';
export const RECEIVE_SELECTED_ORDER = 'RECEIVE_SELECTED_ORDER';
export const RECEIVE_ERROR_SELECTED_ORDER = 'RECEIVE_ERROR_SELECTED_ORDER';
export const REQUEST_ORDER_CANCEL_PRODUCT = 'REQUEST_ORDER_CANCEL_PRODUCT';
export const RECEIVE_ORDER_CANCEL_PRODUCT = 'RECEIVE_ORDER_CANCEL_PRODUCT';
export const RECEIVE_ERROR_ORDER_CANCEL_PRODUCT = 'RECEIVE_ERROR_ORDER_CANCEL_PRODUCT';

export const REQUEST_CANCEL_ORDER = 'REQUEST_CANCEL_ORDER';
export const RECEIVE_CANCEL_ORDER = 'RECEIVE_CANCEL_ORDER';
export const RECEIVE_ERROR_CANCEL_ORDER = 'RECEIVE_ERROR_CANCEL_ORDER';

export const REQUEST_PAYMENT_INFO = 'REQUEST_PAYMENT_INFO';
export const RECEIVE_PAYMENT_INFO = 'RECEIVE_PAYMENT_INFO';
export const RECEIVE_ERROR_PAYMENT_INFO = 'RECEIVE_ERROR_PAYMENT_INFO';

export const FRESHDESK_TICKET_TYPES_SUCCESS = 'FRESHDESK_TICKET_TYPES_SUCCESS';
export const FRESHDESK_FEEDBACK_ATTEMPT = 'FRESHDESK_FEEDBACK_ATTEMPT';
export const FRESHDESK_FEEDBACK_SUCCESS = 'FRESHDESK_FEEDBACK_SUCCESS';
export const FRESHDESK_ERORR = 'FRESHDESK_ERORR';
export const FRESHDESK_FEEDBACK_RECOVER = 'FRESHDESK_FEEDBACK_RECOVER';
export const CLEAR_PAYMENT_INFO = 'CLEAR_PAYMENT_INFO';

export const CHANGE_CURRENT_CURRENCY = 'CHANGE_CURRENT_CURRENCY';

export const BETAOUT_UPDATE = 'BETAOUT_UPDATE';

export const SET_APP_ROUTE = 'SET_APP_ROUTE';
